name: Audit Node Version

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.2'
      - name: Install Dependencies
        run: npm install
      - name: Audit NPM Packages
        run: npm audit