name: Audit NPM Packages

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.2'
      - name: Audit Node Version
        run: npx is-my-node-vulnerable